### ISSUE TITLE
Editor still opens on the side even if add-on disabled

### ISSUE THREAD

**Issue by johan456789** [ijgnd/anki__browser_side_by_side__horizontal_split#1]
Restarting the app doesn't help.

Anki 2.1.15 (442df9d6) Python 3.6.7 Qt 5.12.1 PyQt 5.11.3
Platform: Mac 10.13.6

![image](https://user-images.githubusercontent.com/14802181/71421272-d05dd300-26b4-11ea-9d9b-ef4a598ade40.png)

**Comment by ijgnd** [comment]
Thank you  very much for your report

I just updated the add-on which should fix this error. Does it work for you?

**Comment by johan456789** [comment]
Thank you for the quick update. Yes, it's fixed :)
