### ISSUE TITLE
Minor Annoyance

### ISSUE THREAD

**Issue by drmarmalademd** [ijgnd/anki__browser_side_by_side__horizontal_split#3]
Hello, I am on Anki 2.1.23 on a mac.

Occasionally, when I close out of Anki with a browser window still open, I get the following error message. This is happening more frequently so is becoming quite annoying.

**Error**
An error occurred. Please start Anki while holding down the shift key, which will temporarily disable the add-ons you have installed.
If the issue only occurs when add-ons are enabled, please use the Tools > Add-ons menu item to disable some add-ons and restart Anki, repeating until you discover the add-on that is causing the problem.
When you've discovered the add-on that is causing the problem, please report the issue on the add-on support site.
Debug info:
Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
Platform: Mac 10.15.3
Flags: frz=True ao=True sv=2
Add-ons, last update check: 2020-03-28 09:49:36
Add-ons possibly involved: ⁨Browser TableEditor side-by-side horizontal split⁩

Caught exception:
Traceback (most recent call last):
  File "aqt/progress.py", line 76, in handler
  File "aqt/browser.py", line 713, in callback
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-162>", line 2, in _closeWindow
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 657, in repl
  File "</Applications/Anki.app/Contents/MacOS/decorator.pyc:decorator-gen-154>", line 2, in _closeWindow
  File "anki/hooks.py", line 666, in decorator_wrapper
  File "anki/hooks.py", line 660, in repl
  File "/Users/ahsanrkhan/Library/Application Support/Anki2/addons21/831846358/__init__.py", line 90, in additionalClose
    self.form.splitter.setOrientation(Qt.Vertical)
RuntimeError: wrapped C/C++ object of type QSplitter has been deleted

**Comment by ijgnd** [comment]
Thanks for reporting this issue here. I'm not sure why this error occurs for you. So far I haven't had this error. Maybe I can reproduce it if I use your combination of add-ons and better understand and hopefully then fix it. 

Could you share: from the main window click on Help->About. In the window that opens click the "Copy Debug Info" Button and share the copied text.

**Comment by drmarmalademd** [comment]
I have many add-ons, so it is entirely possible it is a conflict with another one.

Here is my debug info:

    
    Anki 2.1.23 (de9543ff) Python 3.8.0 Qt 5.13.1 PyQt 5.14.1
    Platform: Mac 10.15.3
    Flags: frz=True ao=True sv=2
    Add-ons, last update check: 2020-03-28 09:49:36
    
    
    ===Add-ons (active)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['put_ALL_due_learning_cards_first', 0, 'None', '']
    '' ['review_heatmap', 0, 'None', '']
    AK - No Tags Pop-up ['show_warning_with_no_tags', 0, 'None', '']
    AMBOSS add-on ['0amboss_addon', 2020-02-03T17:28, 'None', '']
    Add Hyperlink ['318752047', 2019-10-27T23:17, 'None', '']
    Add Table ['1237621971', 2020-03-02T21:37, 'None', '']
    Advanced Browser ['874215009', 2020-02-20T17:39, 'None', '']
    Anki Killstreaks ['579111794', 2020-03-10T13:20, 'None', '']
    Anki Simulator ['anki_simulator', 2020-03-25T17:48, 'None', '']
    Batch Editing ['291119185', 2019-09-19T13:04, 'None', '']
    Batch Remove Formatting eg bold italics etc ['1734822644', 2018-09-24T11:34, 'None', '']
    BetterTags ['bettertags', 2020-01-28T15:30, 'None', '']
    Browser Resizer ['1435775540', 2020-02-07T19:39, 'None', mod]
    Browser Search Box Quick Insert Tag Deck Notetype ['1052724801', 2020-03-23T19:22, 'None', mod]
    Browser TableEditor side-by-side horizontal split ['831846358', 2020-01-15T16:51, 'None', mod]
    Clickable Tags v20 Anki 2120 support ['1739176371', 2020-03-13T10:25, 'None', '']
    Cloze Overlapper ['cloze_overlapper', 2019-02-01T07:37, 'None', '']
    Coronavirus Tracker ['1313091126', 2020-03-18T13:59, 'None', '']
    Create Filtered Deck from the Browser ['861263371', 2019-03-01T22:14, 'None', '']
    Custom background image and gear icon ['1210908941', 0, 'None', mod]
    Customize Keyboard Shortcuts ['24411424', 2020-03-11T01:05, 'None', mod]
    Customize Sidebar ['1988760596', 2020-01-16T17:12, 'None', mod]
    Deck name in title 21 ['699175524', 2019-06-26T21:57, 'None', '']
    Edit Field During Review Cloze ['385888438', 2020-03-20T05:16, 'None', mod]
    Extended Card Stats During Review ['1008566916', 2019-03-01T22:14, 'None', '']
    Extended Tag AddEdit Dialog ['1135507717', 2020-03-25T18:31, 'None', mod]
    External Note Editor for the Browser ['browser_external_note_editor', 2020-03-10T13:42, 'None', '']
    Fastbar- with nightmode support ['46611790', 2020-03-20T10:34, 'None', '']
    Free Weekend - or Any Other Day ['742185195', 2020-01-24T10:34, 'None', mod]
    Frozen Fields ['516643804', 2020-02-29T23:12, 'None', '']
    High Yield Tags ['1918380616', 2020-03-10T19:11, 'None', mod]
    Highlight Search Results in the Browser ['225180905', 2019-03-02T18:36, 'None', '']
    Hint Hotkeys ['1844908621', 2019-02-26T13:58, 'None', '']
    HoochieMama Randomize Rev Queue ['1460733408', 2020-02-17T22:14, 'None', '']
    HoochiePapa Randomize New Queue ['1173108619', 2020-02-17T22:14, 'None', '']
    Image Occlusion Enhanced for Anki 21 alpha ['1374772155', 2019-09-19T13:05, 'None', '']
    Image Style Editor ['1593969147', 2020-03-05T23:51, 'None', mod]
    ImageResizer ['1214357311', 2019-02-27T20:33, 'None', '']
    Improved Quizlet to Anki 21 Importer ['538351043', 2020-02-24T19:00, 'None', '']
    Learning Step and Review Interval Retention ['1949865265', 2020-01-11T19:33, 'None', '']
    Mini Format Pack ['295889520', 2019-03-01T22:13, 'None', '']
    More Decks Stats and Time Left ['1556734708', 2020-01-21T08:23, 'None', mod]
    More Overview Stats 21 ['738807903', 2019-02-26T13:51, 'None', mod]
    No Distractions Full Screen Clean review interface  TabletTouch support ['1049863218', 2020-03-28T04:00, 'v4.0', mod]
    Open Added Today from Reviewer ['861864770', 2019-02-22T14:19, 'None', '']
    Opening the same window multiple time ['354407385', 2020-03-09T07:57, 'None', '']
    Pop-up Dictionary beta ['153625306', 2019-06-26T21:52, 'None', '']
    Progress Bar ['2091361802', 2019-03-02T21:27, 'None', mod]
    Progress Graphs and Stats for Learned and Matured Cards ['266436365', 2019-07-31T22:43, 'None', '']
    Quick Colour Changing ['2491935955', 2019-03-02T21:26, 'None', mod]
    ReMemorize Rescheduler with sibling and logging v130 ['323586997', 2020-02-03T13:57, 'None', mod]
    Rebuild All  Empty All for Anki 21 ['1810938259', 2018-07-20T00:40, 'None', '']
    Refocus Card when Reviewing 21 ['1642550423', 2019-03-04T13:20, 'None', '']
    Resize images in editor ['1103084694', 2020-03-21T04:58, 'None', mod]
    Special Fields ['1102281552', 2020-03-24T09:45, 'None', mod]
    Speed Focus Mode auto-alert auto-reveal auto-fail/good ['1046608507', 2019-06-02T05:11, 'None', '']
    Spelling Police ['1410276506', 2020-03-02T21:13, 'None', mod]
    Symbols As You Type ['2040501954', 2020-03-17T23:36, 'None', '']
    Symbols ['1461102936', 2019-04-23T09:37, 'None', mod]
    TagSelectorV2 ['1022577188', 2018-09-16T23:06, 'None', '']
    The KING of Button Add-ons ['374005964', 2020-03-20T10:34, 'None', mod]
    True Retention ['613684242', 2019-06-26T21:55, 'None', '']
    Visual Feedback for Reviews ['review_feedback', 2020-01-29T14:43, 'None', '']
    Web Browser - Search terms Import texts and images automatically ['864545277', 2020-01-19T14:46, 'None', mod]
    Zoom 21 ['1846592880', 2020-03-02T21:37, 'None', '']
    add-on dialog searchfilter bar ['561945101', 2020-01-21T18:38, 'None', '']
    when is next learning card due today due ['563204849', 2019-12-22T23:49, 'None', mod]
    
    ===IDs of active AnkiWeb add-ons===
    1008566916 1022577188 1046608507 1049863218 1052724801 1102281552 1103084694 1135507717 1173108619 1210908941 1214357311 1237621971 1313091126 1374772155 1410276506 1435775540 1460733408 1461102936 153625306 1556734708 1593969147 1642550423 1734822644 1739176371 1810938259 1844908621 1846592880 1918380616 1949865265 1988760596 2040501954 2091361802 225180905 24411424 2491935955 266436365 291119185 295889520 318752047 323586997 354407385 374005964 385888438 46611790 516643804 538351043 561945101 563204849 579111794 613684242 699175524 738807903 742185195 831846358 861263371 861864770 864545277 874215009
    
    ===Add-ons (inactive)===
    (add-on provided name [Add-on folder, installed at, version, is config changed])
    '' ['popup_dictionary', 0, 'None', mod]
    '' ['zoom', 0, 'None', '']
    Additional Card Fields Fork for 21 ['744725736', 2020-02-17T14:42, 'None', mod]
    Answer Button Sounds ['679615590', 2020-02-20T10:10, 'None', '']
    Blitzkrieg II - Advanced Browser Sidebar BETA7 ['564851917', 2020-02-25T13:57, 'None', '']
    Browser Card Info Bar ['2140680811', 2020-02-19T09:19, 'None', mod]
    Button Colours Good Again ['2494384865', 2020-02-09T07:18, 'None', mod]
    Card Info During Review ['2179254157', 2019-12-17T03:31, 'None', '']
    Clickable Tags v11 ['380714095', 2020-03-22T09:56, 'None', '']
    Convert Subdecks to Tag Hierarchy ['1172858842', 2020-02-23T17:03, 'None', '']
    Dancing Baloney Allows changing wallpapers with live preview ['378638814', 2020-03-27T01:28, 'None', '']
    Echelon - Improved Hierarchical Tags for Anki 21 - Unsupported ['829533913', 2020-03-02T21:37, 'None', '']
    Enhance main window ['877182321', 2020-02-15T21:51, 'None', mod]
    Fastbar another toolbar for Anki 21 beta ['1955978390', 2019-09-03T22:10, 'None', '']
    Full Screen Toggle ['1612375712', 2020-02-23T22:46, 'None', '']
    Hierarchical Tags 2  Anki 2117 support ['594329229', 2020-01-29T10:05, 'None', '']
    Load Balanced Scheduler ['208879074', 2019-07-23T22:37, 'None', '']
    Maximum image height and width in card editor ['229181581', 2020-02-20T03:10, 'None', mod]
    Night Mode ['1496166067', 2019-06-26T21:54, 'None', '']
    Pokemanki ['633922407', 2020-03-03T22:10, 'None', '']
    Puppy Reinforcement ['puppy_reinforcement', 2020-02-05T02:16, 'None', '']
    Redesign ['1914733489', 2020-02-29T17:46, 'None', '']
    Remaining time for Anki 21 ['1508357010', 2020-03-28T08:43, 'None', '']
    Reset Ease ['947935257', 2019-11-14T18:58, 'None', '']
    Spell Checker ['spell_checker', 0, 'None', '']
    Syllabus - Anki Statistics and Export by Tag and Deck ['668156440', 2020-01-19T14:52, 'None', mod]
    load balancer ['1417170896', 2020-02-17T15:02, 'None', '']
    porting_clickable_tags ['porting_clickable_tags', 0, 'None', '']

**Comment by ijgnd** [comment]
I closed  anki with the browser open many times with your add-ons and didn't get an error on my machine. At the moment I have no idea but maybe later.

**Comment by drmarmalademd** [comment]
I’ll continue to look into this by messing around with the add-one I have. Thanks for checking.

**Comment by ijgnd** [comment]
reopen this if needed
