### ISSUE TITLE
is it possible to stop resizing the search bar?

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [ijgnd/anki__browser_side_by_side__horizontal_split#4]
Hi,

I end up limiting the width of the vertical split because it eats up the search field for no good reason. Is it possible to change this?

Thanks :)

**Comment by ijgnd** [comment]
I agree that a search bar that always covers the whole width would be better. 

But the anki browser is not designed for this. As far as I see I would have to modify a lot in the anki browser in a fragile way (by overwriting built-in stuff) which might cause problems with other add-ons and which is more likely to break in the future and which would be much more work. So I won't include this for the forseeable future.

At the moment I'm working on an add-on that is similar to my "Quick insert" add-on but for the whole search bar. Maybe this can somewhat help. There's no fixed release date.

If I missed something or you still have a question/problem just reopen the issue.

**Comment by thiswillbeyourgithub** [comment]
Maybe a workaround would be to simply display the content of the search bar in a text element at this location : 
![screenshot](https://user-images.githubusercontent.com/26625900/85227089-a0289000-b3ca-11ea-948a-6850391c24d6.png)


The problem to me is more that I can't see what I typed rather than accurately reading the field.

What do you think? It should require only minimal editing don't you think?

**Comment by ijgnd** [comment]
the unused grey area that you surround is part of a webpage like element that is embedded within Anki. I would need some custom html and javascript code for this.

the only webpage like element in the browser is the editor, the rest is made with PyQt where I need use the python programing language. So I can't just say in my add-on "duplicate/move the search bar" into another position. I would have to recreate the searchbar and connect it to the python components that are outside of the editor webview.

Maybe some professional coder who daily writes js and python would consider what's needed as "minimal editing" but for me it would be much more effort. For me the first solution of redesigning the browser would probably be quicker.

**Comment by thiswillbeyourgithub** [comment]
I'm sorry my message wasn't clear. I meant just display the content of the search bar, not recreate the actual bar. It would be quite ugly but would help.

**Comment by ijgnd** [comment]
Just mirroring the search term is much more doable but it's probably still quite complicated so at the moment I won't create this.

I have just uploaded a new version of this add-on with the option "when narrow move search bar to extra line". It's not really wide but at least wider. If you notice a problem let me know. In the coming days I'll also upload my multi-line search dialog add-on.

**Comment by thiswillbeyourgithub** [comment]
IT IS WAY BETTER. To me it's really an improvement.

Thank you very much!

**Comment by thiswillbeyourgithub** [comment]
Hey, just found out that the addon "bettersearch" enables multiline search field. Just in case anyone else has the same kind of problem : https://ankiweb.net/shared/info/1052724801


edit : haha just found out you are the creator of this addon. This really shows how impactful you are. Thanks a lot!!
