### ISSUE TITLE
Causes wrong positioning of card/note switch in 2.1.45

### ISSUE THREAD

**Issue by kleinerpirat** [ijgnd/anki__browser_side_by_side__horizontal_split#5]
Hi ijgnd!

Just a little heads-up about a layout issue that will take effect with Anki 2.1.45.
As @RumovZ [pointed out on the forum](https://forums.ankiweb.net/t/anki-2-1-45-alpha/10061/40?u=kleinerpirat), the side-by-side view of your add-on causes the new card/note switch ([`qt/aqt/switch.py`](https://github.com/ankitects/anki/blob/a3e3e56f2b7d1e1ea0693d3ae6d3da7b1c7ea3b7/qt/aqt/switch.py)) to be positioned on top of the search bar instead of to the left of it.

#### With side-by-side view:
![image](https://user-images.githubusercontent.com/62722460/119458918-8364ad00-bd3d-11eb-95e9-933d57d4345b.png)
#### What it should look like:
![image](https://user-images.githubusercontent.com/62722460/119458964-8eb7d880-bd3d-11eb-8f1c-4e6df11df3d0.png)

I can only guess it stems from Anki using a grid layout instead of a [QHBoxLayout](https://doc.qt.io/qt-5/qhboxlayout.html) for that upper part. Do you think this has to be solved within Anki itself or can you work around it?

Thank you for this great add-on and all the best!

**Comment by RumovZ** [comment]
Wouldn't be a big deal to use a QHBoxLayout instead. I wasn't aware that using a grid would complicate things for add-ons.

**Comment by ijgnd** [comment]
Thanks for your posts.

The searchbar has always been in a gridlayout in 2.1 afaik. Some of my add-ons - including this one and e.g. my [BetterSearch](https://ankiweb.net/shared/info/1052724801) rearrange the contents of the gridlayout based on the default layout of older anki versions. Adding the new c/n switch breaks my assumptions and thus my add-ons. I think I need to adjust my add-ons.

I wonder if there's anything that could be done to make such modifications more future-proof. But if you as an add-on author want to force a layout of elements in a qgridlayout you'll always try to set them exactly which means that you'll have to handle all existing elements which will break once a new element like a c/n switch is introduced? I think a gui_hook that passed/collected elements for the qgridlayout would only solve some cases?

@kleinerpirat: If for the side-by-side add-on you change the setting `when narrow move search bar to extra line` to `false` the problem should disappear? At least it does for me. If this also fixes it for you I'll just remove the effect of this setting for .45+

@rumovz: The c/n switch is a great addition to Anki - It's very useful and makes the card-note distinction much more prominent which I think should also help beginners. Thank you very much for it.

**Comment by kleinerpirat** [comment]
> If for the side-by-side add-on you change the setting when narrow move search bar to extra line to false the problem should disappear?

This fixed the issue for me too. Thank you!
